filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/suricata/eve.json
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["https://192.168.20.30:9200"]
  username: "admin"
  password: "SecretPassword"
  ssl.verification_mode: none
  index: "suricata-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "suricata"
setup.template.pattern: "suricata-*"
